{application,faliseProject,
             [{description,"An OTP application"},
              {vsn,"0.1.0"},
              {registered,[]},
              {mod,{faliseProject_app,[]}},
              {applications,[kernel,stdlib,cowboy]},
              {env,[]},
              {modules,[faliseProject_app,faliseProject_sup]},
              {maintainers,[]},
              {licenses,["Apache 2.0"]},
              {links,[]}]}.
